#!/usr/bin/env bash
# deploy.sh — Build, deploy, and write frontend env vars automatically
# Usage: ./scripts/deploy.sh [--guided]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
ENV_FILE="$FRONTEND_DIR/.env.local"

# ─── Pre-flight checks ────────────────────────────────────────────────────────
echo "==> Checking tools..."
command -v aws   >/dev/null 2>&1 || { echo "ERROR: aws CLI not found"; exit 1; }
command -v sam   >/dev/null 2>&1 || { echo "ERROR: sam CLI not found"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 not found"; exit 1; }

AWS_REGION="${AWS_DEFAULT_REGION:-ap-southeast-1}"
echo "    Region: $AWS_REGION"
echo "    Account: $(aws sts get-caller-identity --query Account --output text)"

# ─── SAM build ────────────────────────────────────────────────────────────────
echo ""
echo "==> Building Lambda functions..."
cd "$BACKEND_DIR"
sam build --parallel --cached

# ─── SAM deploy ───────────────────────────────────────────────────────────────
echo ""
echo "==> Deploying stack..."
if [[ "${1:-}" == "--guided" ]]; then
  sam deploy --guided
else
  sam deploy
fi

# ─── Read outputs from CloudFormation ────────────────────────────────────────
echo ""
echo "==> Reading stack outputs..."
STACK_NAME=$(grep 'stack_name' "$BACKEND_DIR/samconfig.toml" | head -1 | sed 's/.*= *"\(.*\)"/\1/')
STACK_NAME="${STACK_NAME:-zage-stack}"

get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

API_URL=$(get_output ApiUrl)
USER_POOL_ID=$(get_output UserPoolId)
USER_POOL_CLIENT_ID=$(get_output UserPoolClientId)
UPLOAD_BUCKET=$(get_output UploadBucket)
CLOUDFRONT_URL=$(get_output CloudFrontUrl)
FRONTEND_BUCKET=$(get_output FrontendBucket)

echo "    ApiUrl:             $API_URL"
echo "    UserPoolId:         $USER_POOL_ID"
echo "    UserPoolClientId:   $USER_POOL_CLIENT_ID"
echo "    UploadBucket:       $UPLOAD_BUCKET"
echo "    CloudFrontUrl:      $CLOUDFRONT_URL"
echo "    FrontendBucket:     $FRONTEND_BUCKET"

# ─── Write frontend .env.local ────────────────────────────────────────────────
echo ""
echo "==> Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Re-run ./scripts/deploy.sh to refresh these values.

VITE_API_URL=$API_URL
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_UPLOAD_BUCKET=$UPLOAD_BUCKET
VITE_REGION=$AWS_REGION
EOF

echo "    Written."

# ─── Build and deploy frontend ────────────────────────────────────────────────
echo ""
read -rp "==> Build and deploy frontend to S3/CloudFront? [y/N] " DEPLOY_FRONTEND
if [[ "${DEPLOY_FRONTEND,,}" == "y" ]]; then
  echo "==> Installing frontend dependencies..."
  cd "$FRONTEND_DIR"
  npm ci

  echo "==> Building React app..."
  npm run build

  echo "==> Syncing to s3://$FRONTEND_BUCKET ..."
  aws s3 sync dist/ "s3://$FRONTEND_BUCKET" \
    --delete \
    --cache-control "public, max-age=31536000, immutable" \
    --exclude "index.html"

  # index.html must not be cached aggressively (SPA routing)
  aws s3 cp dist/index.html "s3://$FRONTEND_BUCKET/index.html" \
    --cache-control "no-cache, no-store, must-revalidate"

  # Invalidate CloudFront
  DIST_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CloudFrontUrl'].OutputValue" \
    --output text 2>/dev/null || true)

  CF_DIST=$(aws cloudfront list-distributions \
    --query "DistributionList.Items[?Origins.Items[0].DomainName=='$FRONTEND_BUCKET.s3.$AWS_REGION.amazonaws.com'].Id" \
    --output text 2>/dev/null || true)

  if [[ -n "$CF_DIST" ]]; then
    echo "==> Invalidating CloudFront distribution $CF_DIST..."
    aws cloudfront create-invalidation --distribution-id "$CF_DIST" --paths "/*" >/dev/null
  fi

  echo ""
  echo "==> Frontend deployed!"
  echo "    URL: $CLOUDFRONT_URL"
fi

echo ""
echo "==> Deployment complete!"
echo ""
echo "    Next steps for frontend developer:"
echo "    1. Update frontend/src/aws-config.js with Amplify config"
echo "    2. Replace mock auth in Login.jsx / Signup.jsx"
echo "    3. Replace mock API calls in api.js"
echo ""
echo "    API URL:   $API_URL"
echo "    App URL:   $CLOUDFRONT_URL"
